language: c
install: bash -e .travis-ci-install.sh
script: bash -e .travis-ci.sh
cache: apt
sudo: true
os:
- linux
- osx
env:
  matrix:
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.2
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.2
  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.2.2
  - OCAML_VERSION=3.12.1 OPAM_VERSION=1.2.2
  - OCAML_VERSION=4.03.0 OPAM_VERSION=1.2.2
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.1
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.1
  global:
    secure: f94YSGGMPGsuELDBBWZR4fRokWSyb6MKfojT2pec4jHLpp2TTct1dE/hM49qfzpDQaiiwzj+sYak1s2qYVqgbwSnE6e6x5oL8UEKRZE2EOArdJOqjqOprMK/76Couvmy+HBYPEmk3CswFkrYnDP1bRu/NogG8z9/OtOA/mD6evoqeV7CaBHz8ac1Qd2hkD/pTgHaAIqvzXTX95cspkX2wK+wuVXti6ZMhy43ikDBaJNeUIzBvihA6ddAHoiKKy1tYF0g/67v68LEcE26AEaruCMH4dIc0r+MYz5hclLcEh0joVtlPQ9UYi8fNOAxJHNU2UtYRkWmpqnK4/WfqhzLTnIvixUjFQiDarZski7P3a7aTf2jvsJWqMqpz87xm8Ldjr7SaAhAaN7wW8ksgS8Ksm3k8F/zWXCTwsTueCfxsuBpPNMf4f/4L/hyfe7iJI9IdsiyqeZQ9aK791iA3qCC3Qk5/YlTg+Qim1sE8QmCFYy0dxw+XtbQW8JSNxxbK5rfAVYNHcAv+79SQas9oZzYtN06zrWFeU80rkvvnr9HLjcAIGUYXLSdun7WZm1uVYQNitNFc5V2fgo8E6oVZEscaMHqa7fWp7ZoiDett3QRMSeh+tl0jXTsyFpTzTdgNDyTLM682n5R+LgyattyhnhLQMF2V2vr4EroCFkvt7Dq12Q=
matrix:
  allow_failures:
  - env: OCAML_VERSION=4.03.0
  exclude:
  - os: osx
    env: OPAM_VERSION=1.2.1
  - os: osx
    env: OPAM_VERSION=1.2.0
  - os: osx
    env: OPAM_VERSION=1.1.1
  - os: osx
    env: OCAML_VERSION=4.01.0
  - os: osx
    env: OCAML_VERSION=4.00.1
  - os: osx
    env: OCAML_VERSION=3.12.1
# notifications:
#   email:
#   - opam-commits@lists.ocaml.org
#   irc:
#   - chat.freenode.net#opam
